---
name: publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  GRADLE_SWITCHES: "--console=plain --info --stacktrace --no-daemon"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'moderneinc'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: "gradle"
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCR_KEY }}
      - uses: google-github-actions/setup-gcloud@v1.1.0
      - name: publish-candidate
        if: contains(github.ref, '-rc.')
        timeout-minutes: 30
        run: ./gradlew ${GRADLE_SWITCHES} -Preleasing -Prelease.disableGitChecks=true -Prelease.useLastTag=true -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} build candidate publishPlugins
      - name: publish-release
        if: (!contains(github.ref, '-rc.'))
        timeout-minutes: 30
        run: ./gradlew ${GRADLE_SWITCHES} -Preleasing -Prelease.disableGitChecks=true -Prelease.useLastTag=true -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} build final publishPlugins
